language: node_js
node_js:
  - "6"
  - "7"
env:
  - CONTINUOUS_INTEGRATION=1 CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make test
after_script:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
